name: Keep App Alive - Método Brandness

on:
  schedule:
    # Executa a cada 4 minutos
    - cron: '*/4 * * * *'
  workflow_dispatch: # Permite execução manual

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping App
        run: |
          echo "Enviando ping para manter app ativo..."
          
          # URL do app
          APP_URL="https://69b74673-0ef2-49f3-ba9a-bc22a1c316ad-00-w4i0twjv1w27.picard.replit.dev"
          
          # Fazer ping com timeout
          RESPONSE=$(curl -s -w "%{http_code}|%{time_total}" -o /dev/null --max-time 30 "$APP_URL")
          HTTP_CODE=$(echo $RESPONSE | cut -d'|' -f1)
          TIME=$(echo $RESPONSE | cut -d'|' -f2)
          
          echo "Status: $HTTP_CODE | Tempo: ${TIME}s"
          
          # Verificar se o ping foi bem-sucedido
          if [ "$HTTP_CODE" = "200" ]; then
            echo "✅ Ping bem-sucedido para Método Brandness"
          else
            echo "⚠️ Ping retornou status: $HTTP_CODE"
            # Tentar novamente após 30 segundos
            sleep 30
            RETRY_RESPONSE=$(curl -s -w "%{http_code}" -o /dev/null --max-time 30 "$APP_URL")
            echo "Retry status: $RETRY_RESPONSE"
          fi
          
          # Log com timestamp
          echo "Ping executado em: $(date)"